### ISSUE TITLE
Use pyup or remove its badge from README.rst

### ISSUE THREAD

**Issue by s-weigand** [oz123/pytest-localftpserver#12]
At the moment a broken pyup badge is in the `README.rst`, which is a not too pretty artifact from the  coociecutter template. The solution for this would to eigther drop the badge or start using pyup.

Pros and Cons on using pyup:
**Pros**:
* pyup makes automated PRs when new versions of dependencies are released (automated testing due to the CIs, which garantees functionality new versions of dependencies)

**Cons**:
* can be "spammy" if many updates of dependencies are released
* will lead to merge conficts, with its own PRs, if ignored too long

PS.: Pyup only triggers on fixed versions (i.e.: `pytest==3.0.5`) not on minimum requirements (i.e.: `pytest>=3.0.5`), so by convention this should only affect `requirements_dev.txt` since it is bad practice to fix versions in the `setup.py`

**Comment by oz123** [comment]
Can you  make a PR for this?

**Comment by s-weigand** [comment]
Sure, you just need to register the project at pyup and I will make a PR with fixed versions in the `requirements_dev.txt`

**Comment by oz123** [comment]
done.
