### ISSUE TITLE
Test stuck on running

### ISSUE THREAD

**Issue by e-belair** [oz123/pytest-localftpserver#128]
Hi, I'm facing an issue while running tests. The test runner still runs after all tests passed and I'm obliged to force tests to stop.

If I remove the test_get_ftp_con test, everything working fine

This is the test I'm running:
```python
# This is the function to test
def get_ftp_con(config) -> FTP:
    """
    Crée un objet de connection ftp
    Vérifie que le rep de backup existe et se positionne à l'intérieur
    """
    ftp = FTP()
    ftp.connect(config['host'], int(config['port']))
    ftp.login(config['user'], config['pass'])

    ftp_bck_dir = 'backups'
    if ftp_bck_dir not in ftp.nlst():
        ftp.mkd(ftp_bck_dir)

    ftp.cwd(ftp_bck_dir)

    return ftp

# The test
def test_get_ftp_con(ftpserver):
    ftp = get_ftp_con({
        'host': 'localhost',
        'port': ftpserver.server_port,
        'user': ftpserver.username,
        'pass': ftpserver.password
    })
    ftp.quit()
    assert Path(ftpserver.server_home).joinpath('backups').is_dir()
```

![image](https://user-images.githubusercontent.com/596562/111633388-be0a1080-87f5-11eb-8197-f56ee791c9a9.png)

Note: I tried in Pycharm and directly in the cmd line, same behavior

**Comment by s-weigand** [comment]
If I remember right it sometimes happens that the server keeps waiting for a client.
In our tests, we solved this with the following code.

https://github.com/oz123/pytest-localftpserver/blob/e49282187ffc8a0aa3b9b1bb4cd0bec3673ba6c4/tests/test_pytest_localftpserver.py#L73-L87

If that solves your problem, maybe it can be included as a helper function like `ftpserver.ensure_quit_session(ftp_instance)`

**Comment by e-belair** [comment]
unfortunately, it's not working. I also tried to stop the ftpserver manually direct inside the test

```python
def test_get_ftp_con(ftpserver):
    ftp = get_ftp_con({
        'host': 'localhost',
        'port': ftpserver.server_port,
        'user': ftpserver.username,
        'pass': ftpserver.password
    })
    ftp.quit()
    assert Path(ftpserver.server_home).joinpath('sauvegarde_bdd_solutions_a6cmo').is_dir()
    close_client(ftp) # Nothing change
    ftpserver.stop() # Nothing change too
```

**Comment by s-weigand** [comment]
Hmmmm what OS and python version are you using?

**Comment by e-belair** [comment]
I'm using python 3.8.5 on Ubuntu 20.04.2
```
pytest==6.2.2
pytest-localftpserver==1.1.2
pyftpdlib==1.5.6
```
For instance, I'm trying a way to stop the process inside conftest pytest_sessionfinish hook

**Comment by e-belair** [comment]
I tried `close_client` without `ftp.quit()` but nothing change

**Comment by s-weigand** [comment]
Hmmm, I ran our tests on `Ubuntu 20.04` with `Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1` and all passed.
I also tested your code and there was no problem.
So I'm kinda out of ideas and also time atm, maybe @oz123 has some idea what is going on.

The last idea would be are you using your system python or a venv? I used a conda env.

Cheers and good luck need to go.

**Comment by e-belair** [comment]
I'm using venv.
Ok thanks for your help, I'm still investigating ...

**Comment by e-belair** [comment]
When I run in debug mode, the tests seems to force close and I'm getting this error message:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
Maybe it can help

**Comment by oz123** [comment]
A wild guess: the problem is because you are running the tests in PyCharm.
Can you run your code directly in the terminal?

**Comment by e-belair** [comment]
I tried in the terminal and I'm getting the same behavior, pytest won't stop

**Comment by e-belair** [comment]
I've started a new fresh project with only this test and it's working fine. I wonder what can cause this in my other project Oo

**Comment by oz123** [comment]
Can you reduce your code to just one file with the single test? Please also post all the import you use . Is `FTP` the stdlib TPD?

**Comment by e-belair** [comment]
I think I have a clue by reducing tests.
I have one test that check a db connection. If I run this test with ftp tests, I get pytest stuck
If I remove this test only, everything works fine
The weird thing is that I get the problem only if these two tests run together!

**Comment by e-belair** [comment]
Ok I could fix the problem. Inside one test I forgot to close the database connection.
The strange thing is why this problem appear happen only whit ftp tests?! I really don't know :D
If you have any idea I'm curious to know
Anyway I can close this issue now, thanks for your help :)

**Comment by oz123** [comment]
Sorry, I can't help with that. But at least we solved your problem by reducing the surface.
