### ISSUE TITLE
Docs aren't generated properly

### ISSUE THREAD

**Issue by s-weigand** [oz123/pytest-localftpserver#14]
The section `API Documentation` in the docs isn't generated properly.
I think this is due to missing configuration, for `autodoc` (which reads the docstrings from the code) to work, the package need to be installed in a virtual env on readthedocs.
If you add me (handel `s-weigand` ) as developer on read the docs (`Project->Administration->Developers`), I can have a look and fix it.

**Comment by oz123** [comment]
Thanks you for the fix.
